### ISSUE TITLE
Saves (API and dialog)

### ISSUE THREAD

**Issue by tmedwards** [tmedwards/sugarcube-3#1]
## Todo

* [x] There should be a way to export and import the save slots via the `Save` API and the Save dialog.
* [x] Some people have been confused as to what the *Save to Disk…* and *Load from Disk…* buttons actually do—e.g., thinking they export the save slots to disk.  They should probably be moved to a separate section within the dialog, distinct from the slots.
* [x] UI work: Compact the slots a bit by changing fully to icons, if I can pull together a set that makes sense.
* [ ] UI work: Allow authors greater freedom in what can be displayed.
* [ ] UI work: Allow players the ability to name saves—probably author configurable.

## Ideas

* Make slots user nameable or remove the static slots altogether in favor of user nameable entries—e.g., like saves in many PC games.  The latter would still need to be limited in number, due to limited storage resources, so maybe the former would be best.

## Current working demo (ca. 2020-04-20)

![image](https://user-images.githubusercontent.com/101626/79748430-06157000-82d3-11ea-882f-37aae4a139e7.png)

**Comment by Uzume** [comment]
How about make the number of slots be arbitrary and allow paging? This could be author controlled via config options so that the max number of slots displayed per page and max number of pages can be specified. This way we could have a fixed ten slows by just configuring with one page and ten slots per page.

Of course to be really web progressive, there might need to be virtual pages vs. real pages. Maybe ten slots does not fit on a mobile phone screen--however, ten times one is still ten (so SugarCube could create more pages so long as the author's intent is kept). And it would be nice to have unspecified large values to specify display as many as comfortably possible and an unlimited number of pages. It would be nice if those were the defaults (especially if history goes away more save slots will be wanted).

I like moving to icons--less to translate (though you might move the existing text to be a popup hover text explaining icons in case someone does not understand and wants a longer description).

The new import and export concepts are interesting. I almost wonder if it would be good to have something that imports or exports all the slots to/from disk basically snapshotting the entire save storage to and from disk at once. I assume the import and export functions you are thinking of are designed to be on a per save basis. If that is true why not another icon? You would only need one as it too could be modal based on if there is data in the slot or not (import empty slots and export full ones).

If you have import and export per slot, save and load directly to disk is a tad redundant as the same can be accomplished by saving and then exporting (the only down side is the necessity to use save slots which might be limited and direct disk save and load are not).

Player naming of saves is good. I am curious though. What happens to such names across import/export? Lost? Auto file naming suggestions and reverse (filename gets used for naming the slot imported to)? Or are these names to be saved with the rest of the data and then return when the save is imported? Filenames typically have OS restrictions that you might not want to deal with when it comes to slot labeling/naming. Things to think about.

**Comment by tmedwards** [comment]
From the Twine Games discord:

> A way to configure the "Delete All" button, so it was possible to delete all of the Manual saves without deleting the Auto save(s)

Or maybe a button for each.
